name: CI

on:
  push:
    paths:
      - src/**
      - examples/**
      - tests/**
      - Cargo.toml
env:
  RUST_VERSION: "1.94"

jobs:
  test:
    name: Test crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust toolchain
        run: rustup toolchain install ${{ env.RUST_VERSION }} --profile minimal --no-self-update
      - name: Setup rust-cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo check
        run: cargo check

      - name: Cargo build
        run: cargo build --all-features

      - name: Cargo test
        run: cargo test --all-features
